<font size = 1 color="gray">Introducción a la computación numérica y simbólica con Python</font>  
<img src="img/logo-vector-u-tad.jpg" align="left" >

# 6. Matrices

Las aplicaciones del álgebra son ilimitadas. Con `numpy` disponemos de todas las herramientas necesarias para un manejo óptimo de vectores y matrices, algo de lo que carece el core de Python.

In [1]:
# Creación de matrices sin usar numpy.
# 
# Pueden construirse matrices sin recurrir al paquete numpy
# usando listas de listas
A = [[1,2,7],[0.6, 3,4]]
print("Matriz A:",A," filas: ",len(A)," columnas: ",len(A[0]))
print("A[0,0] = ",A[0][0],"; A[1,2] = ",A[1][2])


Matriz A: [[1, 2, 7], [0.6, 3, 4]]  filas:  2  columnas:  3
A[0,0] =  1 ; A[1,2] =  4


Aparentemente esto serviría, pero las operaciones no funcionan como esperamos, porque
Python entiende que son listas.

Esto es lo que ocurre si intentamos sumar matrices.

In [2]:
B = [[1,0,1],[0.4,0,0]]
print("A + B = ",A+B)

A + B =  [[1, 2, 7], [0.6, 3, 4], [1, 0, 1], [0.4, 0, 0]]


El resultado es que Python crea una nueva lista que es la concatenación de A y B, no una suma de matrices.

## Creación

Podríamos crear la clase matriz y definir todas las operaciones, pero para eso ya está `numpy`.

In [4]:
import numpy as np
A = np.array([[1,2,7],[0.6,3,4]])
print("Matriz A")
print(A)
print()
print("filas: ",A.shape[0]," columnas ",A.shape[1])
print("A[0,0] = ",A[0][0],"; A[1,2] = ",A[1][2])
print()
B = np.array([[1,0,1],[0.4,0,0]])
print("Matriz B")
print(B)

Matriz A
[[1.  2.  7. ]
 [0.6 3.  4. ]]

filas:  2  columnas  3
A[0,0] =  1.0 ; A[1,2] =  4.0

Matriz B
[[1.  0.  1. ]
 [0.4 0.  0. ]]


## Operaciones

In [6]:
# Operaciones con matrices
print("Matriz A")
print(A)
print("Matriz B")
print(B)
print()
print("A + B")
print(A+B)
print()
print("A - B")
print(A-B)
print()
print("2 x A")
print(2*A)
print()
# El operador * multiplica elemento a elemento, es decir c[ji] = a[ji] x b [ji]
print("A * B")
print(A*B)

Matriz A
[[1.  2.  7. ]
 [0.6 3.  4. ]]
Matriz B
[[1.  0.  1. ]
 [0.4 0.  0. ]]

A + B
[[2. 2. 8.]
 [1. 3. 4.]]

A - B
[[0.  2.  6. ]
 [0.2 3.  4. ]]

2 x A
[[ 2.   4.  14. ]
 [ 1.2  6.   8. ]]

A * B
[[1.   0.   7.  ]
 [0.24 0.   0.  ]]


El producto de matrices se consigue usando el método dot(). Tal y como hemos definido A y B no pueden multiplicarse porque sus dimensions son incompatibles. Si podríamos multiplicar por la traspuesta de B.

In [7]:
print("Matriz A")
print(A)
Btransp = B.transpose()
print("Matriz B transpuesta")
print(Btransp)
print()
print("C = A x B'")
C = A.dot(Btransp)
print(C)

Matriz A
[[1.  2.  7. ]
 [0.6 3.  4. ]]
Matriz B transpuesta
[[1.  0.4]
 [0.  0. ]
 [1.  0. ]]

C = A x B'
[[8.   0.4 ]
 [4.6  0.24]]


A partir de la versión 3.5 se añadió el operador `@` para multiplicar vectores por matrices.
Supongdamos que tenemos el vector E = [1 1 1] que queremos multiplicar por A.

`A @ E` realiza el producto matricial de A por la traspuesta de E


In [10]:
print("Matriz A")
print(A)
E = np.array([1,1,1])
print("Vector E")
print(E)
print()
print("A @ E")
print(A @ E)

Matriz A
[[1.  2.  7. ]
 [0.6 3.  4. ]]
Vector E
[1 1 1]

A @ E
[10.   7.6]


## Algebra lineal elemental

Como C es una matriz cuadrada podemos calcular su determinante

In [11]:
print("Matriz C")
print(C)
valdet = np.linalg.det(C)
print("El determinante de C es: {:0.4f}".format(valdet))

Matriz C
[[8.   0.4 ]
 [4.6  0.24]]
El determinante de C es: 0.0800


La matriz inversa es la traspuesta de la adjunta dividida por su determinante
$A^{-1} = (A*)'/|A|$

`numpy` no ofrece la adjunta pero sí la inversa

In [12]:
M = np.array([[1,2],[3,4]])
Minv = np.linalg.inv(M)

print("Matriz M")
print(M)
print("Inversa de M")
print(Minv)
print("M * Inv(M)")
MMinv = M@Minv
print(MMinv)

Matriz M
[[1 2]
 [3 4]]
Inversa de M
[[-2.   1. ]
 [ 1.5 -0.5]]
M * Inv(M)
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


Aquí se ve uno de los problemas al trabajar con punto flotante y matrices, el resultado no es exactamente la matriz identidad.

In [13]:
IdMatrix = [[1.,0],[0,1.]]
print( IdMatrix == MMinv)

[[False False]
 [ True False]]


Para solucionarlo, numpy proporciona la función `isclose()` a la que se pasan como parámetros la
tolerancia absoluya y/o relativa

In [14]:
print(np.isclose(IdMatrix, MMinv, rtol=1e-05))

[[ True  True]
 [ True  True]]


Para comprobar si todos los elementos son iguales, se usa `np.allclose()`

In [16]:
print("¿Son iguales la matriz identidad y el producto de una matriz por su inversa?")
print(np.allclose(IdMatrix, MMinv, rtol=1e-5))

¿Son iguales la matriz identidad y el producto de una matriz por su inversa?
True


## Resolución de sistemas de ecuaciones lineales

Si tenemos un sistema de ecuaciones lineales de la siguiente forma:
    
$ a_{11}x_1+a_{12}x_2+ ... +a_{1j}x_j = b_1 $

$ a_{21}x_1+a_{22}x_2+ ... +a_{2j}x_j = b_2 $

$...$

$ a_{m1}x_1+a_{m2}x_2+ ... +a_{mj}x_j = b_m $

Podemos escribirla de una forma compacta como $Ax = B$, donde $A$ es la matriz de los coeficientes de la incógnitas y $B$ el vector columna con los términos independientes. Si llamamos $A^*$ a la matriz $A$ a la que se añade el vector columna $B$, entonces:

- Si $rango(A) = rango(A^*) = j$, el sistema es compatible determinado y los valores pueden obtenerse por la regla de Cramer.

- Si $rango(A) = rango(A^*) < j$, el sistema es compatible indeterminado, hay infinitas soluciones quue son combinaciones lineales. No puede resolverse de forma numérica, sí de simbólica como se verá más adelante.

- Si $rango(A) \not= rango(A^*)$ el sistema de ecuaciones es incompatible.

Ejemplo, encontrar el punto de corte de las rectas

$ -3x + y = -3 $

$ 4x + 2y = 5 $

In [17]:
A = np.array([[-3,1],[4,2]])
b = np.array([-3,5])
print("El rango de A es {:d}".format(np.linalg.matrix_rank(A))," el sistema es compatible determinado")

El rango de A es 2  el sistema es compatible determinado


In [18]:
detA = np.linalg.det(A)

In [19]:
x = np.linalg.det(np.array([[-3,1],[5,2]]))/detA
y = np.linalg.det(np.array([[-3,-3],[4,5]]))/detA
print("Soluciones por Cramer x = {:.4f},y = {:.4f}".format(x,y))

Soluciones por Cramer x = 1.1000,y = 0.3000


El paquete `numpy` ofrece un método para encontrar la solución en un solo paso

In [20]:
solus = np.linalg.solve(A,b)
print("Soluciones con el método solve: ",solus)

Soluciones con el método solve:  [1.1 0.3]


---

<font size="1" color="grey">
    (c) 2020 Javier García Algarra. <a href='https://www.u-tad.com'>www.u-tad.com</a> <br>
Licensed under a Creative Commons Reconocimiento 4.0 Internacional License
</font> 